
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v24.1
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/var/lib/cockroach
    restart: unless-stopped

  plugin-builder:
    image: heroiclabs/nakama-pluginbuilder:3.25.0
    platform: linux/amd64
    environment:
      - GOTOOLCHAIN=local
    entrypoint: []
    command:
      - go
      - build
      - --trimpath
      - --mod=vendor
      - -buildmode=plugin
      - -o
      - ./backend.so
      - .
    working_dir: /backend
    volumes:
      - ./server:/backend


  nakama:
    image: heroiclabs/nakama:3.25.0
    platform: linux/amd64
    depends_on:
      cockroachdb:
        condition: service_started
      plugin-builder:
        condition: service_completed_successfully
    ports:
      - "7349:7349" # gRPC
      - "7350:7350" # HTTP
      - "7351:7351" # WebSocket
    environment:
      - NAKAMA_DATABASE_ADDRESS=root@cockroachdb:26257
    volumes:
      - nakama-data:/nakama/data
      - ./server:/nakama/data/modules
      - ./nakama-config.yml:/nakama/data/nakama-config.yml
    entrypoint:
      - /bin/sh
      - -ecx
      - >
        /nakama/nakama migrate up
        --database.address root@cockroachdb:26257
        &&
        exec /nakama/nakama
        --config /nakama/data/nakama-config.yml
        --name nakama
        --database.address root@cockroachdb:26257
        --logger.level DEBUG
        --session.token_expiry_sec 7200
        --socket.server_key defaultkey
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cockroach-data:
  nakama-data: